import { MigrationInterface, QueryRunner } from 'typeorm';

export class SimplifiedStatusesAndPayments1785127000000 implements MigrationInterface {
  name = 'SimplifiedStatusesAndPayments1785127000000';

  async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`CREATE TYPE "production_order_status_new" AS ENUM ('DRAFT', 'ORDERED', 'CANCELLED')`);
    await queryRunner.query(`ALTER TABLE "production_orders" ALTER COLUMN "status" DROP DEFAULT`);
    await queryRunner.query(`
      ALTER TABLE "production_orders"
      ALTER COLUMN "status" TYPE "production_order_status_new"
      USING (
        CASE
          WHEN "status"::text IN ('IN_PROGRESS', 'COMPLETED') THEN 'ORDERED'
          ELSE "status"::text
        END
      )::"production_order_status_new"
    `);
    await queryRunner.query(`DROP TYPE "production_order_status"`);
    await queryRunner.query(`ALTER TYPE "production_order_status_new" RENAME TO "production_order_status"`);
    await queryRunner.query(`ALTER TABLE "production_orders" ALTER COLUMN "status" SET DEFAULT 'DRAFT'`);

    await queryRunner.query(`CREATE TYPE "payment_status" AS ENUM ('UNPAID', 'PARTIALLY_PAID', 'PAID')`);
    await queryRunner.query(`
      ALTER TABLE "production_orders"
      ADD COLUMN "payment_status" "payment_status" NOT NULL DEFAULT 'UNPAID'
    `);
    await queryRunner.query(`
      CREATE TABLE "payments" (
        "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "production_order_id" BIGINT NOT NULL,
        "amount" NUMERIC(12,2) NOT NULL,
        "paid_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
        "notes" TEXT,
        "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
        CONSTRAINT "PK_payments" PRIMARY KEY ("id"),
        CONSTRAINT "CK_payments_positive" CHECK ("amount" > 0),
        CONSTRAINT "FK_payments_order" FOREIGN KEY ("production_order_id")
          REFERENCES "production_orders"("id") ON DELETE CASCADE ON UPDATE CASCADE
      )
    `);
    await queryRunner.query(`CREATE INDEX "IDX_payments_order" ON "payments" ("production_order_id")`);
  }

  async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE "payments"`);
    await queryRunner.query(`ALTER TABLE "production_orders" DROP COLUMN "payment_status"`);
    await queryRunner.query(`DROP TYPE "payment_status"`);
    await queryRunner.query(`CREATE TYPE "production_order_status_old" AS ENUM ('DRAFT', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')`);
    await queryRunner.query(`ALTER TABLE "production_orders" ALTER COLUMN "status" DROP DEFAULT`);
    await queryRunner.query(`
      ALTER TABLE "production_orders"
      ALTER COLUMN "status" TYPE "production_order_status_old"
      USING (
        CASE WHEN "status"::text = 'ORDERED' THEN 'IN_PROGRESS' ELSE "status"::text END
      )::"production_order_status_old"
    `);
    await queryRunner.query(`DROP TYPE "production_order_status"`);
    await queryRunner.query(`ALTER TYPE "production_order_status_old" RENAME TO "production_order_status"`);
    await queryRunner.query(`ALTER TABLE "production_orders" ALTER COLUMN "status" SET DEFAULT 'DRAFT'`);
  }
}
