import { MigrationInterface, QueryRunner } from 'typeorm';

export class InitialSchema1785123958400 implements MigrationInterface {
  name = 'InitialSchema1785123958400';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TYPE "production_order_status" AS ENUM (
        'DRAFT',
        'IN_PROGRESS',
        'COMPLETED',
        'CANCELLED'
      )
    `);

    await queryRunner.query(`
      CREATE TABLE "customers" (
        "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "business_name" VARCHAR(200) NOT NULL,
        "trade_name" VARCHAR(200),
        "tax_id" VARCHAR(20),
        "address" TEXT,
        "city" VARCHAR(100),
        "phone" VARCHAR(50),
        "email" VARCHAR(200),
        "contact_name" VARCHAR(200),
        "logo_path" TEXT,
        "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
        "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
        CONSTRAINT "PK_customers" PRIMARY KEY ("id")
      )
    `);

    await queryRunner.query(`
      CREATE TABLE "locations" (
        "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "name" VARCHAR(100) NOT NULL,
        "city" VARCHAR(100) NOT NULL,
        "address" TEXT,
        "is_active" BOOLEAN NOT NULL DEFAULT true,
        "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
        CONSTRAINT "PK_locations" PRIMARY KEY ("id")
      )
    `);

    await queryRunner.query(`
      CREATE TABLE "production_orders" (
        "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "order_number" VARCHAR(50) NOT NULL,
        "customer_id" BIGINT NOT NULL,
        "location_id" BIGINT,
        "title" VARCHAR(250) NOT NULL,
        "execution_address" TEXT,
        "start_date" DATE,
        "estimated_completion_date" DATE,
        "completion_date" DATE,
        "status" "production_order_status" NOT NULL DEFAULT 'DRAFT',
        "requested_by" VARCHAR(200),
        "notes" TEXT,
        "subtotal" NUMERIC(12,2) NOT NULL DEFAULT 0,
        "discount" NUMERIC(12,2) NOT NULL DEFAULT 0,
        "total" NUMERIC(12,2) NOT NULL DEFAULT 0,
        "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
        "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
        CONSTRAINT "PK_production_orders" PRIMARY KEY ("id"),
        CONSTRAINT "UQ_production_orders_order_number"
          UNIQUE ("order_number"),
        CONSTRAINT "FK_production_orders_customer"
          FOREIGN KEY ("customer_id")
          REFERENCES "customers"("id")
          ON DELETE RESTRICT
          ON UPDATE CASCADE,
        CONSTRAINT "FK_production_orders_location"
          FOREIGN KEY ("location_id")
          REFERENCES "locations"("id")
          ON DELETE SET NULL
          ON UPDATE CASCADE
      )
    `);

    await queryRunner.query(`
      CREATE TABLE "production_order_items" (
        "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "production_order_id" BIGINT NOT NULL,
        "description" TEXT NOT NULL,
        "quantity" NUMERIC(12,2) NOT NULL DEFAULT 1,
        "unit_price" NUMERIC(12,2) NOT NULL DEFAULT 0,
        "subtotal" NUMERIC(12,2) NOT NULL DEFAULT 0,
        "display_order" INTEGER NOT NULL DEFAULT 0,
        "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
        CONSTRAINT "PK_production_order_items" PRIMARY KEY ("id"),
        CONSTRAINT "FK_production_order_items_order"
          FOREIGN KEY ("production_order_id")
          REFERENCES "production_orders"("id")
          ON DELETE CASCADE
          ON UPDATE CASCADE
      )
    `);

    await queryRunner.query(`
      CREATE TABLE "invoices" (
        "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "production_order_id" BIGINT NOT NULL,
        "invoice_number" VARCHAR(100),
        "issue_date" DATE,
        "amount" NUMERIC(12,2),
        "storage_path" TEXT NOT NULL,
        "original_filename" TEXT NOT NULL,
        "mime_type" VARCHAR(100),
        "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
        CONSTRAINT "PK_invoices" PRIMARY KEY ("id"),
        CONSTRAINT "FK_invoices_production_order"
          FOREIGN KEY ("production_order_id")
          REFERENCES "production_orders"("id")
          ON DELETE CASCADE
          ON UPDATE CASCADE
      )
    `);

    await queryRunner.query(`
      CREATE INDEX "IDX_production_orders_customer"
      ON "production_orders" ("customer_id")
    `);

    await queryRunner.query(`
      CREATE INDEX "IDX_production_orders_status"
      ON "production_orders" ("status")
    `);

    await queryRunner.query(`
      CREATE INDEX "IDX_production_order_items_order"
      ON "production_order_items" ("production_order_id")
    `);

    await queryRunner.query(`
      INSERT INTO "locations" ("name", "city")
      VALUES
        ('Sede Lima', 'Lima'),
        ('Sede Trujillo', 'Trujillo')
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      DROP INDEX IF EXISTS "IDX_production_order_items_order"
    `);

    await queryRunner.query(`
      DROP INDEX IF EXISTS "IDX_production_orders_status"
    `);

    await queryRunner.query(`
      DROP INDEX IF EXISTS "IDX_production_orders_customer"
    `);

    await queryRunner.query(`
      DROP TABLE IF EXISTS "invoices"
    `);

    await queryRunner.query(`
      DROP TABLE IF EXISTS "production_order_items"
    `);

    await queryRunner.query(`
      DROP TABLE IF EXISTS "production_orders"
    `);

    await queryRunner.query(`
      DROP TABLE IF EXISTS "locations"
    `);

    await queryRunner.query(`
      DROP TABLE IF EXISTS "customers"
    `);

    await queryRunner.query(`
      DROP TYPE IF EXISTS "production_order_status"
    `);
  }
}
